FORMAT: 1A
HOST: http://api.procur.com

# Procur

# Group Users
User related resources of the **Procur API**

##All Users [/users]

### Show [GET]

+ Response 200 (application/json)

        [
            {
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "emailVerified": true,
                "profileComplete": false,
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z",
                "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
            },
            {
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "emailVerified": true,
                "profileComplete": false,
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z",
                "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
            }
        ]
        
##Single User [/users/{id}]

+ Parameters
    + id (string) ... ID of the User object


###Show [GET]

+ Response 200 (application/json)

        {
            "firstName": "Doctor",
            "lastName": "Strangelove",
            "email": "dstrangelove@procur.com",
            "emailVerified": true,
            "profileComplete": false,
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z",
            "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
        }
      
###Update [PUT]

+ Request (application/json)

        {
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
        }
        
+ Response 200
        
        {
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
            "emailVerified": true,
            "profileComplete": false,
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z",
            "token": "$2a$50$lccTmLsCO/328vKdgSwHpu8vnTamdsox98I2hcwOVfMfiwhAg97kW"
        }

###Deactivate [DELETE]

+ Request (application/json)

        {
            
        }
        
+ Response 200

        {
            "firstName": "Doctor",
            "lastName": "Strangelove",
            "email": "dstrangelove@procur.com",
            "emailVerified": true,
            "profileComplete": false,
            "active": false,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z",
            "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
        }
        
# Group Companies
Company related resources of the **Procur API**

##All Companies [/companies]

### Show [GET]

+ Response 200

        {
            _id: ObjectId("53a1f4f65e974a08005ea206"),
            active: true,
            buyer: true,
            createdAt: ISODate("2014-06-18T20:22:14.937Z"),
            email: "dstrangelove@procur.com",
            employeeCount: "25",
            faxCountryCode: "1",
            faxExtension: "",
            faxNumber: "5555555555",
            handle: "strangelove",
            industry: "technology",
            name: "Doomsday Machines Inc.",
            phoneExtension: "",
            phoneNumber: "4048499521",
            phoneNumberCountryCode: "1",
            supplier: true,
            updatedAt: ISODate("2014-06-18T20:24:18.155Z"),
            user: "53a1f4c85e974a08005ea204",
            website: "http://procur.com"
        }
        
### Create [POST]

+ Request (application/json)

        {
            name: "Doomsday Machines, Inc.",
            phoneNumberCountryCode: "1",
            phoneNumber: "5555555555",
            phoneExtension: "1",
            email: "dstrangelove@procur.com",
            website: "http://procur.com",
            industry: "technology",
            employeeCount: "25",
        }
        
+ Response 201

        {
            _id: ObjectId("53a1f4f65e974a08005ea206"),
            active: true,
            createdAt: ISODate("2014-06-18T20:22:14.937Z"),
            email: "dstrangelove@procur.com",
            employeeCount: "25",
            faxCountryCode: "1",
            faxExtension: "",
            faxNumber: "5555555555",
            handle: "strangelove",
            industry: "technology",
            name: "Doomsday Machines Inc.",
            phoneExtension: "",
            phoneNumber: "4048499521",
            phoneNumberCountryCode: "1",
            updatedAt: ISODate("2014-06-18T20:24:18.155Z"),
            user: "53a1f4c85e974a08005ea204",
            website: "http://procur.com"
        }
        
##Single Company [/companies/{id}]

+ Parameters
    + id (string) ... ID of the Company object

### Show [GET]

+ Response 200

        {
            _id: ObjectId("53a1f4f65e974a08005ea206"),
            active: true,
            buyer: true,
            createdAt: ISODate("2014-06-18T20:22:14.937Z"),
            email: "dstrangelove@procur.com",
            employeeCount: "25",
            faxCountryCode: "1",
            faxExtension: "",
            faxNumber: "5555555555",
            handle: "strangelove",
            industry: "technology",
            name: "Doomsday Machines Inc.",
            phoneExtension: "",
            phoneNumber: "3333333333",
            phoneNumberCountryCode: "1",
            supplier: true,
            updatedAt: ISODate("2014-06-18T20:24:18.155Z"),
            user: "53a1f4c85e974a08005ea204",
            website: "http://procur.com"
        }

### Update [PUT]

+ Request (application/json)

        {
            name: "Mineshaft Gaps, LLC",
            phoneNumberCountryCode: "1",
            phoneNumber: "3333333333",
            phoneExtension: "1",
            email: "jripper@procur.com",
            website: "http://procur.com",
            industry: "technology",
            employeeCount: "25",
        }
        
+ Response 200

        {
            _id: ObjectId("53a1f4f65e974a08005ea206"),
            active: true,
            buyer: true,
            createdAt: ISODate("2014-06-18T20:22:14.937Z"),
            email: "jripper@procur.com",
            employeeCount: "25",
            faxCountryCode: "1",
            faxExtension: "",
            faxNumber: "3333333333",
            handle: "strangelove",
            industry: "technology",
            name: "Mineshaft Gaps, LLC",
            phoneExtension: "",
            phoneNumber: "5555555555",
            phoneNumberCountryCode: "1",
            supplier: true,
            updatedAt: ISODate("2014-06-18T20:24:18.155Z"),
            user: "53a1f4c85e974a08005ea204",
            website: "http://procur.com"
        }
        
### Deactivate [DELETE]

+ Response 200

        {
            result: "Company successfully deactivated"
        }
        
##Company Members [/companies/{id}/members]

+ Parameters
    + id (string) ... ID of the Company object

### Show [GET]

+ Response 200

        [
            {
                _id: ObjectId("53a1f4f65e974a08005ea206"),
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            },
            {
                _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
                "firstName": "Jack",
                "lastName": "Ripper",
                "email": "jripper@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            }
        ]
        
### Invite Member [POST]

+ Request (application/json)

        {
            userId: "53a1fgf42ef74a08001ea2a6",
        }
        
+ Response 201

        {
            _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z"
        }
        
##Single Company Member [/companies/{id}/members/{userId}]

+ Parameters
    + id (string) ... ID of the Company object
    + userId (string) ... ID of the User object

### Show [GET]

+ Response 200

        {
            _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z"
        }
        
### Modify [PUT]
        
+ Response 501

        {
            "Whoops."
        }
        
        
### Kick Member [DELETE]

+ Response 200

        {
            _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z"
        }

##Member Invitations [/companies/{id}/invitations]

### Show all pending invitations [GET]

+ Response 200

        [
            {
                _id: ObjectId("53a1f4f65e974a08005ea206"),
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            },
            {
                _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
                "firstName": "Jack",
                "lastName": "Ripper",
                "email": "jripper@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            }
        ]
        
### Invite user to company [POST]
        
+ Response 200

        {
            userId: "53a1f4f65e974a08005ea206"
        }
        
##Single Invitation [/companies/{id}/invitations/{userId}]

### Show [GET]

+ Response 200

        {
            _id: ObjectId("53a1f4f65e974a08005ea206"),
            "firstName": "Doctor",
            "lastName": "Strangelove",
            "email": "dstrangelove@procur.com",
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z"
        }

### Revoke Pending Invitation [DELETE]

+ Request (application/json)

        {
            userId: "53a1f4f65e974a08005ea206"
        }
        
+ Response 200

        {
            _id: ObjectId("53a1f4f65e974a08005ea206"),
            "firstName": "Doctor",
            "lastName": "Strangelove",
            "email": "dstrangelove@procur.com",
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z"
        }
        
##Accepted Invitations [/companies/{id}/invitations/accepted]

### Show all accepted invitations [GET]

+ Response 200

        [
            {
                _id: ObjectId("53a1f4f65e974a08005ea206"),
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            },
            {
                _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
                "firstName": "Jack",
                "lastName": "Ripper",
                "email": "jripper@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            }
        ]
        
##Rejected Invitations [/companies/{id}/invitations/rejected]

### Show all rejected invitations [GET]

+ Response 200

        [
            {
                _id: ObjectId("53a1f4f65e974a08005ea206"),
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            },
            {
                _id: ObjectId("53a1fgf42ef74a08001ea2a6"),
                "firstName": "Jack",
                "lastName": "Ripper",
                "email": "jripper@procur.com",
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z"
            }
        ]
        
# Group Buyers

## Single Buyer [/buyers/{Id}]

### Show [GET]

+ Request (application/json)

        {
        
        }

+ Response 200

        {
            "_id": ObjectId("53c171d80b144d0800071be8"),
            "contact": { 
                "name": "Iam Developer",
                "position": "Purchasing Manager",
                "email": "ideveloper@acme.com",
            },
            "createdAt": ISODate("2014-07-12T17:35:20.780Z"),
            "updatedAt": ISODate("2014-07-12T17:35:21.314Z"),
            "company": "53c16e2b186bbc0800ff2c03",
            "companyType": "Association",
            "dba": "ACME Systems",
            "logo": "53c16e2b186bbc0800edcd",
            "duns": "123489589",
            "acceptedCurrencies": [ "USD" ],
            "acceptedPaymentTerms": [ "MoneyGram" ],
            "active": true,
            "tradePreferences": {
                "preferredSupplierLanguage": "Chinese (Jin)",
                "preferredSupplierLocation": "Algeria",
                "preferredSupplierType": "Affiliate Merchant"
            },
            "languages": [ "Chinese (Cantonese)" ],
            "locations": [ "53c16e2b186bbc3400ff2c60" ],
            "socialMedia": {
                "facebook": "100000126516331",
                "google+": "+ACMESystems",
                "instagram": "ACMEPhotos",
                "linkedIn": "acmesystems",
                "pinterest": "acmepins",
                "twitter": "@acmesystems",
                "tumblr": "ACMESystems"
            },
            "profileLink": {
                "title": "Supplier Trade Kit",
                "url": "https://www.acme.com/supplierkit.html"
            },
            "companyDescription": "Lorem ipsum...",
            "productDescription": "Ipsum lorem...",
            "assets": [ "241b530a1fc356bf826c7589610cb928" ],
            "photos": [ "bd8a7c51fcb4f9c3391e59e0c4efaf39" ],
            "responsibilityStatements": {
                "environmentalSustainability": "Lorem ipsum...",
                "qualitySourcing": "Lorem ipsum...",
                "workplaceSafety": "Lorem ipsum...",
                "laborEducationTraining": "Lorem ipsum...",
                "reinvestment": "Lorem ipsum..."
            }
        }

# Group Suppliers

# Group Locations

# Group Assets

# Group Messages

# Group RFX