FORMAT: 1A
HOST: http://api.procur.com

# Procur

# Group Users
User related resources of the **Procur API**

##All Users [/users]

### Show [GET]
    
+ Request (application/json)
    
        {
            
        }
        

+ Response 201 (application/json)

        [
            {
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "emailVerified": true,
                "profileComplete": false,
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z",
                "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
            },
            {
                "firstName": "Doctor",
                "lastName": "Strangelove",
                "email": "dstrangelove@procur.com",
                "emailVerified": true,
                "profileComplete": false,
                "active": true,
                "createdAt": "2014-06-15T16:10:58.710Z",
                "updatedAt": "2014-06-15T16:10:58.710Z",
                "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
            }
        ]
        
##Single User [/users/{id}]

###Show [GET]

+ Request (application/json)
    
        {

        }
        

+ Response 200 (application/json)

        {
            "firstName": "Doctor",
            "lastName": "Strangelove",
            "email": "dstrangelove@procur.com",
            "emailVerified": true,
            "profileComplete": false,
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z",
            "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
        }
      
###Update [PUT]

+ Request (application/json)

        {
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
        }
        
+ Response 200
        
        {
            "firstName": "Jack",
            "lastName": "Ripper",
            "email": "jripper@procur.com",
            "emailVerified": true,
            "profileComplete": false,
            "active": true,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z",
            "token": "$2a$50$lccTmLsCO/328vKdgSwHpu8vnTamdsox98I2hcwOVfMfiwhAg97kW"
        }

###Deactivate [DELETE]

+ Request (application/json)

        {
            
        }
        
+ Response 200

        {
            "firstName": "Doctor",
            "lastName": "Strangelove",
            "email": "dstrangelove@procur.com",
            "emailVerified": true,
            "profileComplete": false,
            "active": false,
            "createdAt": "2014-06-15T16:10:58.710Z",
            "updatedAt": "2014-06-15T16:10:58.710Z",
            "token": "$2a$50$lccTmLXCO/328vKdgSwHpu8vnTamdWox98I2hcwx3OVfMwhAg97kW"
        }
        
# Group Companies
Company related resources of the **Procur API**

##All Companies [/companies]

### Show [GET]

+ Request (application/json)

        {
        
        }
        
+ Response 200

        {
            
        }
        
# Group Buyers

# Group Suppliers

# Group Locations

# Group Assets

# Group Messages

# Group RFX